[[main]]
    name = "Posts"
    pageRef = "posts"
    weight = 10

[[main]]
    name = "Talks"
    pageRef = "talks"
    weight = 20

[[main]]
    name = "Publications"
    pageRef = "publications"
    weight = 25

[[main]]
    name = "Research"
    pageRef = "research"
    weight = 30
    
[[main]]
    name = "About me"
    pageRef = "about-me"
    weight = 100

[[footer]]
    name = "Contact"
    pageRef = "contact"
    weight = 10

[[footer]]
    name = "Imprint"
    pageRef = "imprint"
    weight = 20