name: Deploy Hugo site via SCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: true 
        fetch-depth: 0

    - name: Set up Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    - name: Build the Hugo site
      run: hugo --minify

    - name: Deploy via SCP using Password
      env:
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        REMOTE_PATH: ${{ secrets.REMOTE_PATH }}
      run: |
        sshpass -p "$SSH_PASSWORD" scp -r -o StrictHostKeyChecking=no public/* $REMOTE_USER@$REMOTE_HOST:$REMOTE_PATH